[{'qa_pairs': 
    {'query': "What are the key features of the Women's Campside Oxfords, including materials, construction, and design elements?",
   'answer': "The Women's Campside Oxfords are designed with a super-soft canvas material that provides a broken-in feel fFrom the first wear. They feature thick cushioning with a comfortable EVA innersole that includes Cleansport NXT® antimicrobial odor control. The innersole has a vintage hunt, fish, and camping motif, along with a moderate arch contour for support. The shoes also have an EVA foam midsole for additional cushioning and support, and a chain-tread-inspired molded rubber outsole with a modified chain-tread pattern. The approximate weight of the shoes is 1 lb. 1 oz. per pair."
   }},
 {'qa_pairs': {'query': 'What are the dimensions of the small and medium sizes of the Recycled Waterhog Dog Mat, and what materials are used in its construction?',
   'answer': 'The small size of the Recycled Waterhog Dog Mat measures 18" x 28", while the medium size measures 22.5" x 34.5". The mat is constructed from 24 oz. polyester fabric made from 94% recycled materials and features a rubber backing.'}},
 {'qa_pairs': {'query': "What are the key features of the Infant and Toddler Girls' Coastal Chill Swimsuit, and how do they contribute to the swimsuit's functionality and safety?",
   'answer': "The Infant and Toddler Girls' Coastal Chill Swimsuit features bright colors, ruffles, and exclusive whimsical prints, making it visually appealing for toddlers. It is made from four-way-stretch and chlorine-resistant fabric, which helps the swimsuit maintain its shape and resist snags. Additionally, the fabric is rated UPF 50+, providing the highest level of sun protection by blocking 98% of harmful UV rays. The swimsuit includes crossover no-slip straps and a fully lined bottom for a secure fit and maximum coverage. For maintenance, it is recommended to machine wash and line dry the swimsuit for best results."}},
 {'qa_pairs': {'query': 'What are the key features and benefits of the Refresh Swimwear V-Neck Tankini, and how does its fabric contribute to both comfort and environmental sustainability?',
   'answer': "The Refresh Swimwear V-Neck Tankini is designed for comfort and functionality, making it suitable for activities like swimming and stand-up paddleboarding (SUP). Key features include a fitted design that sits close to the body, lightweight racerback straps for ease of wear, and a flattering V-neck silhouette. The tankini is made from a premium Italian-blend fabric that is breathable, quick-drying, and abrasion-resistant. It consists of 82% recycled nylon and 18% Lycra® spandex, with the lining made of 90% recycled nylon and 10% Lycra® spandex. This fabric not only provides the perfect amount of stretch but is also environmentally friendly due to the use of recycled mateFrials. Additionally, the tankini offers UPF 50+ sun protection, ensuring the highest level of protection against harmful UV rays. Care instructions recommend handwashing and line drying to maintain the garment's quality."}},
 {'qa_pairs': {'query': 'What are the key features of the EcoFlex 3L Storm Pants, and how do they enhance the experience of outdoor activities?',
   'answer': 'The EcoFlex 3L Storm Pants are designed with several key features that enhance the experience of outdoor activities. They utilize state-of-the-art TEK O2 technology, which provides exceptional breathability, making them suitable for a variety of activities year-round, including skiing. The pants are made from a three-layer nylon shell that offers waterproof protection, ensuring that users stay dry in wet conditions. Additional features include weather-blocking gaiters that keep out rain and snow, full side zips for easy on and off over boots, and multiple pockets (two zippered hand pockets and a thigh pocket) for convenient storage. These features collectively contribute to comfort and functionality, making the pants ideal for outdoor enthusiasts.'}}]